# Generated by Django 4.2 on 2023-04-16 21:41

import car.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cus', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='123 Street', max_length=100)),
                ('contact', models.CharField(default='0123456789', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='prd', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=car.models.product_directory_path)),
                ('description', models.TextField(blank=True, default='This is the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('specifications', models.TextField(blank=True, default='This is the product', null=True)),
                ('type', models.CharField(blank=True, default='This is the product', max_length=100, null=True)),
                ('stock_count', models.CharField(blank=True, default='8', max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='car', unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='Bejing x7', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='This is the product', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.customer')),
            ],
            options={
                'verbose_name_plural': 'Car',
            },
        ),
    ]
