# Generated by Django 4.2 on 2023-04-16 22:11

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='sup', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='123 Street', max_length=100)),
                ('contact', models.CharField(default='0123456789', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Supplier',
            },
        ),
    ]
