# Generated by Django 4.2 on 2023-04-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='specifications',
        ),
    ]
