# Generated by Django 4.2 on 2023-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_report_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default="1.99", max_digits=65),
        ),
    ]
