# Generated by Django 4.2 on 2023-04-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0003_products_cost_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="title",
            new_name="name",
        ),
    ]
