# Generated by Django 4.2 on 2023-04-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('car interior', 'Car Interior'), ('car exterior', 'Car Exterior'), ('car accessories', 'Car Accessories')], default='car interior', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=65),
        ),
    ]
