# Generated by Django 4.2 on 2023-04-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_products_category_products_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('car interior', 'Car Interior'), ('car exterior', 'Car Exterior'), ('car accessories', 'Car Accessories'), ('car care services', 'Car Care Services')], default='car interior', max_length=100),
        ),
    ]
